- name: latex-environment
  path: https://github.com/quarto-ext/latex-environment
  author: "[Quarto Extensions](https://github.com/quarto-ext/)"
  description: |
    Quarto extension to output custom LaTeX environments.
    
    ```sh
    quarto add quarto-ext/latex-environment
    ```
  type: [shortcodes-filters]
  categories: []

