name: "Release: Bump Version & Create Release"

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create GitHub App token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}

      - name: Get GitHub App User ID
        id: get-user-id
        shell: bash
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
        run: echo "user-id=$(gh api "/users/${APP_SLUG}[bot]" --jq .id)" >> "${GITHUB_OUTPUT}"

      - name: Git Config
        env:
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
          USER_ID: ${{ steps.get-user-id.outputs.user-id }}
        shell: bash
        run: |
          git config --global user.name "${APP_SLUG}[bot]"
          git config --global user.email "${USER_ID}+${APP_SLUG}[bot]@users.noreply.github.com"

      - name: Bump Version
        id: bump-version
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          COMMIT: "ci: bump version for release :rocket:"
          BRANCH: ci/bump-version
        outputs:
          version: ${{ steps.bump-version.outputs.version }}
        shell: bash
        run: |
          if git show-ref --quiet refs/heads/${BRANCH}; then
            echo "Branch ${BRANCH} already exists."
            git branch -D "${BRANCH}"
            git push origin --delete "${BRANCH}"
          fi
          git checkout -b "${BRANCH}"
          DATE=$(date +%Y-%m-%d)
          VERSION=$(date +%Y.%m.%d)
          sed -i "s/^version:.*/version: ${VERSION}/" CITATION.cff
          sed -i "s/^date-released:.*/date-released: \"${DATE}\"/" CITATION.cff
          git add CITATION.cff || echo "No changes to add"
          git commit -m "${COMMIT}" || echo "No changes to commit"
          git push --force origin ${BRANCH} || echo "No changes to push"
          sleep 5
          gh pr create --fill-first --base "main" --head "${BRANCH}" --label "Type: CI/CD :robot:"
          sleep 5
          gh pr merge --auto --squash --delete-branch
          echo "version=${VERSION}" >> "${GITHUB_OUTPUT}"
          echo "date=${DATE}" >> "${GITHUB_OUTPUT}"

      - name: Release extension on GitHub
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          VERSION: ${{ steps.bump-version.outputs.version }}
          DATE: ${{ steps.bump-version.outputs.date }}
        shell: bash
        run: |
          sleep 5
          gh release create ${VERSION} --title ${DATE} --generate-notes
